"""update userid to be generated by uuid

Revision ID: 266a7006e738
Revises: ca45e3d6e670
Create Date: 2026-05-08 06:29:39.620631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266a7006e738'
down_revision = 'ca45e3d6e670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
